version: '3.9'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
    secrets:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY

