version: '3.9'
name: defang-django
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        # published: 8000 # uncomment for local dev
    environment:
      - DEBUG=False # set to "True" for local dev
