#!/bin/sh

# Get the branch being pushed
protected_branch="branchProtection"
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Check if the current branch is the protected branch
if [ "$current_branch" = "$protected_branch" ]; then
  echo "🚫 Direct pushes to the '$protected_branch' branch are not allowed."
  echo "Please create a pull request instead."
  exit 1
fi

# Allow the push if it's not the protected branch
exit 0