version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    # - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    # - err113
    # - errcheck
    - errchkjson
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustruct
    - fatcontext
    # - forbidigo
    - forcetypeassert
    # - funlen
    # - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    - gochecksumtype
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - gofumpt
    - goheader
    # - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    # - gosmopolitan
    # - govet
    - grouper
    # - importas
    # - inamedparam
    - ineffassign
    # - interfacebloat
    - intrange
    # - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    # - musttag
    - nakedret
    # - nestif
    - nilerr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    - perfsprint
    # - prealloc
    - predeclared
    - promlinter
    # - protogetter
    - reassign
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    # - sqlclosecheck
    # - staticcheck
    # - stylecheck
    # - tagalign
    # - tagliatelle
    # - testableexamples
    # - testifylint
    # - testpackage
    # - tenv
    # - thelper - more trouble than it's worth
    # - tparallel
    - unconvert
    - unparam
    - unused
    # - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    gosec:
      config:
        G306: "0o644"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
