version: '3'
name: nextjs
services:
  web:
    restart: unless-stopped
    # domainname: mydomain.com # if you want to use your own domain
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - target: 3000
        mode: ingress
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M