package azure

type Location string

const (
	LocationAsia                Location = "asia"
	LocationAsiaPacific         Location = "asiapacific"
	LocationAustralia           Location = "australia"
	LocationAustraliaCentral    Location = "australiacentral"
	LocationAustraliaCentral2   Location = "australiacentral2"
	LocationAustraliaEast       Location = "australiaeast"
	LocationAustraliaSouthEast  Location = "australiasoutheast"
	LocationAustriaEast         Location = "austriaeast"
	LocationBrazil              Location = "brazil"
	LocationBrazilSouth         Location = "brazilsouth"
	LocationBrazilSouthEast     Location = "brazilsoutheast"
	LocationBrazilUS            Location = "brazilus"
	LocationCanada              Location = "canada"
	LocationCanadaCentral       Location = "canadacentral"
	LocationCanadaEast          Location = "canadaeast"
	LocationCentralIndia        Location = "centralindia"
	LocationCentralUS           Location = "centralus"
	LocationCentralUSEuap       Location = "centraluseuap"
	LocationCentralUSStage      Location = "centralusstage"
	LocationChileCentral        Location = "chilecentral"
	LocationEastAsia            Location = "eastasia"
	LocationEastAsiaStage       Location = "eastasiastage"
	LocationEastUS              Location = "eastus"
	LocationEastUS2             Location = "eastus2"
	LocationEastUS2Euap         Location = "eastus2euap"
	LocationEastUS2Stage        Location = "eastus2stage"
	LocationEastUSStage         Location = "eastusstage"
	LocationEastUSStg           Location = "eastusstg"
	LocationEurope              Location = "europe"
	LocationFrance              Location = "france"
	LocationFranceCentral       Location = "francecentral"
	LocationFranceSouth         Location = "francesouth"
	LocationGermany             Location = "germany"
	LocationGermanyNorth        Location = "germanynorth"
	LocationGermanyWestCentral  Location = "germanywestcentral"
	LocationGlobal              Location = "global"
	LocationIndia               Location = "india"
	LocationIndonesia           Location = "indonesia"
	LocationIndonesiaCentral    Location = "indonesiacentral"
	LocationIsrael              Location = "israel"
	LocationIsraelCentral       Location = "israelcentral"
	LocationItaly               Location = "italy"
	LocationItalyNorth          Location = "italynorth"
	LocationJapan               Location = "japan"
	LocationJapanEast           Location = "japaneast"
	LocationJapanWest           Location = "japanwest"
	LocationJioIndiaCentral     Location = "jioindiacentral"
	LocationJioIndiaWest        Location = "jioindiawest"
	LocationKorea               Location = "korea"
	LocationKoreaCentral        Location = "koreacentral"
	LocationKoreaSouth          Location = "koreasouth"
	LocationMalaysia            Location = "malaysia"
	LocationMalaysiaWest        Location = "malaysiawest"
	LocationMexico              Location = "mexico"
	LocationMexicoCentral       Location = "mexicocentral"
	LocationNewZealand          Location = "newzealand"
	LocationNewZealandNorth     Location = "newzealandnorth"
	LocationNorthCentralUS      Location = "northcentralus"
	LocationNorthCentralUSStage Location = "northcentralusstage"
	LocationNorthEurope         Location = "northeurope"
	LocationNorway              Location = "norway"
	LocationNorwayEast          Location = "norwayeast"
	LocationNorwayWest          Location = "norwaywest"
	LocationPoland              Location = "poland"
	LocationPolandCentral       Location = "polandcentral"
	LocationQatar               Location = "qatar"
	LocationQatarCentral        Location = "qatarcentral"
	LocationSingapore           Location = "singapore"
	LocationSouthAfrica         Location = "southafrica"
	LocationSouthAfricaNorth    Location = "southafricanorth"
	LocationSouthAfricaWest     Location = "southafricawest"
	LocationSouthCentralUS      Location = "southcentralus"
	LocationSouthCentralUSStage Location = "southcentralusstage"
	LocationSouthCentralUSStg   Location = "southcentralusstg"
	LocationSoutheastAsia       Location = "southeastasia"
	LocationSoutheastAsiaStage  Location = "southeastasiastage"
	LocationSouthIndia          Location = "southindia"
	LocationSpain               Location = "spain"
	LocationSpainCentral        Location = "spaincentral"
	LocationSweden              Location = "sweden"
	LocationSwedenCentral       Location = "swedencentral"
	LocationSwedenSouth         Location = "swedensouth"
	LocationSwitzerland         Location = "switzerland"
	LocationSwitzerlandNorth    Location = "switzerlandnorth"
	LocationSwitzerlandWest     Location = "switzerlandwest"
	LocationTaiwan              Location = "taiwan"
	LocationUae                 Location = "uae"
	LocationUaeCentral          Location = "uaecentral"
	LocationUaeNorth            Location = "uaenorth"
	LocationUK                  Location = "uk"
	LocationUKSouth             Location = "uksouth"
	LocationUKWest              Location = "ukwest"
	LocationUnitedStates        Location = "unitedstates"
	LocationUnitedStatesEuap    Location = "unitedstateseuap"
	LocationWestCentralUS       Location = "westcentralus"
	LocationWestEurope          Location = "westeurope"
	LocationWestIndia           Location = "westindia"
	LocationWestUS              Location = "westus"
	LocationWestUS2             Location = "westus2"
	LocationWestUS2Stage        Location = "westus2stage"
	LocationWestUS3             Location = "westus3"
	LocationWestUSStage         Location = "westusstage"
)

func (l Location) String() string {
	return string(l)
}

func (l Location) Ptr() *string {
	if l == "" {
		return nil
	}
	s := string(l)
	return &s
}
