version: '3.9'
services:
  django-crm:
    build: .
    ports: 
      - mode: ingress
        target: 8000
    environment:
      - DB_HOST=db
      - DEBUG=False
    volumes: [".:/code"]
    depends_on:
      - db
  db:
    image: postgres:14
    volumes: ["./tmp/postgres:/var/lib/postgresql/data/"]
    environment:
    - POSTGRES_DB=mydatabase
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypassword
    ports:
      - mode: host
        target: 5432