// protos/io/defang/v1/fabric.proto

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: io/defang/v1/fabric.proto

package defangv1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/DefangLabs/defang/src/protos/io/defang/v1"
	connect_go "github.com/bufbuild/connect-go"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion1_7_0

const (
	// FabricControllerName is the fully-qualified name of the FabricController service.
	FabricControllerName = "io.defang.v1.FabricController"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FabricControllerGetStatusProcedure is the fully-qualified name of the FabricController's
	// GetStatus RPC.
	FabricControllerGetStatusProcedure = "/io.defang.v1.FabricController/GetStatus"
	// FabricControllerGetVersionProcedure is the fully-qualified name of the FabricController's
	// GetVersion RPC.
	FabricControllerGetVersionProcedure = "/io.defang.v1.FabricController/GetVersion"
	// FabricControllerTokenProcedure is the fully-qualified name of the FabricController's Token RPC.
	FabricControllerTokenProcedure = "/io.defang.v1.FabricController/Token"
	// FabricControllerRevokeTokenProcedure is the fully-qualified name of the FabricController's
	// RevokeToken RPC.
	FabricControllerRevokeTokenProcedure = "/io.defang.v1.FabricController/RevokeToken"
	// FabricControllerTailProcedure is the fully-qualified name of the FabricController's Tail RPC.
	FabricControllerTailProcedure = "/io.defang.v1.FabricController/Tail"
	// FabricControllerUpdateProcedure is the fully-qualified name of the FabricController's Update RPC.
	FabricControllerUpdateProcedure = "/io.defang.v1.FabricController/Update"
	// FabricControllerDeployProcedure is the fully-qualified name of the FabricController's Deploy RPC.
	FabricControllerDeployProcedure = "/io.defang.v1.FabricController/Deploy"
	// FabricControllerGetProjectDomainProcedure is the fully-qualified name of the FabricController's
	// GetProjectDomain RPC.
	FabricControllerGetProjectDomainProcedure = "/io.defang.v1.FabricController/GetProjectDomain"
	// FabricControllerGetProcedure is the fully-qualified name of the FabricController's Get RPC.
	FabricControllerGetProcedure = "/io.defang.v1.FabricController/Get"
	// FabricControllerDeleteProcedure is the fully-qualified name of the FabricController's Delete RPC.
	FabricControllerDeleteProcedure = "/io.defang.v1.FabricController/Delete"
	// FabricControllerDestroyProcedure is the fully-qualified name of the FabricController's Destroy
	// RPC.
	FabricControllerDestroyProcedure = "/io.defang.v1.FabricController/Destroy"
	// FabricControllerPublishProcedure is the fully-qualified name of the FabricController's Publish
	// RPC.
	FabricControllerPublishProcedure = "/io.defang.v1.FabricController/Publish"
	// FabricControllerSubscribeProcedure is the fully-qualified name of the FabricController's
	// Subscribe RPC.
	FabricControllerSubscribeProcedure = "/io.defang.v1.FabricController/Subscribe"
	// FabricControllerGetServicesProcedure is the fully-qualified name of the FabricController's
	// GetServices RPC.
	FabricControllerGetServicesProcedure = "/io.defang.v1.FabricController/GetServices"
	// FabricControllerGenerateFilesProcedure is the fully-qualified name of the FabricController's
	// GenerateFiles RPC.
	FabricControllerGenerateFilesProcedure = "/io.defang.v1.FabricController/GenerateFiles"
	// FabricControllerStartGenerateProcedure is the fully-qualified name of the FabricController's
	// StartGenerate RPC.
	FabricControllerStartGenerateProcedure = "/io.defang.v1.FabricController/StartGenerate"
	// FabricControllerGenerateStatusProcedure is the fully-qualified name of the FabricController's
	// GenerateStatus RPC.
	FabricControllerGenerateStatusProcedure = "/io.defang.v1.FabricController/GenerateStatus"
	// FabricControllerDebugProcedure is the fully-qualified name of the FabricController's Debug RPC.
	FabricControllerDebugProcedure = "/io.defang.v1.FabricController/Debug"
	// FabricControllerSignEULAProcedure is the fully-qualified name of the FabricController's SignEULA
	// RPC.
	FabricControllerSignEULAProcedure = "/io.defang.v1.FabricController/SignEULA"
	// FabricControllerCheckToSProcedure is the fully-qualified name of the FabricController's CheckToS
	// RPC.
	FabricControllerCheckToSProcedure = "/io.defang.v1.FabricController/CheckToS"
	// FabricControllerPutSecretProcedure is the fully-qualified name of the FabricController's
	// PutSecret RPC.
	FabricControllerPutSecretProcedure = "/io.defang.v1.FabricController/PutSecret"
	// FabricControllerDeleteSecretsProcedure is the fully-qualified name of the FabricController's
	// DeleteSecrets RPC.
	FabricControllerDeleteSecretsProcedure = "/io.defang.v1.FabricController/DeleteSecrets"
	// FabricControllerListSecretsProcedure is the fully-qualified name of the FabricController's
	// ListSecrets RPC.
	FabricControllerListSecretsProcedure = "/io.defang.v1.FabricController/ListSecrets"
	// FabricControllerGetConfigsProcedure is the fully-qualified name of the FabricController's
	// GetConfigs RPC.
	FabricControllerGetConfigsProcedure = "/io.defang.v1.FabricController/GetConfigs"
	// FabricControllerPutConfigProcedure is the fully-qualified name of the FabricController's
	// PutConfig RPC.
	FabricControllerPutConfigProcedure = "/io.defang.v1.FabricController/PutConfig"
	// FabricControllerDeleteConfigsProcedure is the fully-qualified name of the FabricController's
	// DeleteConfigs RPC.
	FabricControllerDeleteConfigsProcedure = "/io.defang.v1.FabricController/DeleteConfigs"
	// FabricControllerListConfigsProcedure is the fully-qualified name of the FabricController's
	// ListConfigs RPC.
	FabricControllerListConfigsProcedure = "/io.defang.v1.FabricController/ListConfigs"
	// FabricControllerPutDeploymentProcedure is the fully-qualified name of the FabricController's
	// PutDeployment RPC.
	FabricControllerPutDeploymentProcedure = "/io.defang.v1.FabricController/PutDeployment"
	// FabricControllerListDeploymentsProcedure is the fully-qualified name of the FabricController's
	// ListDeployments RPC.
	FabricControllerListDeploymentsProcedure = "/io.defang.v1.FabricController/ListDeployments"
	// FabricControllerCreateUploadURLProcedure is the fully-qualified name of the FabricController's
	// CreateUploadURL RPC.
	FabricControllerCreateUploadURLProcedure = "/io.defang.v1.FabricController/CreateUploadURL"
	// FabricControllerDelegateSubdomainZoneProcedure is the fully-qualified name of the
	// FabricController's DelegateSubdomainZone RPC.
	FabricControllerDelegateSubdomainZoneProcedure = "/io.defang.v1.FabricController/DelegateSubdomainZone"
	// FabricControllerDeleteSubdomainZoneProcedure is the fully-qualified name of the
	// FabricController's DeleteSubdomainZone RPC.
	FabricControllerDeleteSubdomainZoneProcedure = "/io.defang.v1.FabricController/DeleteSubdomainZone"
	// FabricControllerGetDelegateSubdomainZoneProcedure is the fully-qualified name of the
	// FabricController's GetDelegateSubdomainZone RPC.
	FabricControllerGetDelegateSubdomainZoneProcedure = "/io.defang.v1.FabricController/GetDelegateSubdomainZone"
	// FabricControllerSetOptionsProcedure is the fully-qualified name of the FabricController's
	// SetOptions RPC.
	FabricControllerSetOptionsProcedure = "/io.defang.v1.FabricController/SetOptions"
	// FabricControllerWhoAmIProcedure is the fully-qualified name of the FabricController's WhoAmI RPC.
	FabricControllerWhoAmIProcedure = "/io.defang.v1.FabricController/WhoAmI"
	// FabricControllerTrackProcedure is the fully-qualified name of the FabricController's Track RPC.
	FabricControllerTrackProcedure = "/io.defang.v1.FabricController/Track"
	// FabricControllerDeleteMeProcedure is the fully-qualified name of the FabricController's DeleteMe
	// RPC.
	FabricControllerDeleteMeProcedure = "/io.defang.v1.FabricController/DeleteMe"
	// FabricControllerVerifyDNSSetupProcedure is the fully-qualified name of the FabricController's
	// VerifyDNSSetup RPC.
	FabricControllerVerifyDNSSetupProcedure = "/io.defang.v1.FabricController/VerifyDNSSetup"
	// FabricControllerGetSelectedProviderProcedure is the fully-qualified name of the
	// FabricController's GetSelectedProvider RPC.
	FabricControllerGetSelectedProviderProcedure = "/io.defang.v1.FabricController/GetSelectedProvider"
	// FabricControllerSetSelectedProviderProcedure is the fully-qualified name of the
	// FabricController's SetSelectedProvider RPC.
	FabricControllerSetSelectedProviderProcedure = "/io.defang.v1.FabricController/SetSelectedProvider"
	// FabricControllerCanIUseProcedure is the fully-qualified name of the FabricController's CanIUse
	// RPC.
	FabricControllerCanIUseProcedure = "/io.defang.v1.FabricController/CanIUse"
	// FabricControllerEstimateProcedure is the fully-qualified name of the FabricController's Estimate
	// RPC.
	FabricControllerEstimateProcedure = "/io.defang.v1.FabricController/Estimate"
	// FabricControllerPreviewProcedure is the fully-qualified name of the FabricController's Preview
	// RPC.
	FabricControllerPreviewProcedure = "/io.defang.v1.FabricController/Preview"
	// FabricControllerGenerateComposeProcedure is the fully-qualified name of the FabricController's
	// GenerateCompose RPC.
	FabricControllerGenerateComposeProcedure = "/io.defang.v1.FabricController/GenerateCompose"
)

// FabricControllerClient is a client for the io.defang.v1.FabricController service.
type FabricControllerClient interface {
	GetStatus(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Status], error)
	GetVersion(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Version], error)
	Token(context.Context, *connect_go.Request[v1.TokenRequest]) (*connect_go.Response[v1.TokenResponse], error)
	RevokeToken(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	Tail(context.Context, *connect_go.Request[v1.TailRequest]) (*connect_go.ServerStreamForClient[v1.TailResponse], error)
	// Deprecated: do not use.
	Update(context.Context, *connect_go.Request[v1.Service]) (*connect_go.Response[v1.ServiceInfo], error)
	Deploy(context.Context, *connect_go.Request[v1.DeployRequest]) (*connect_go.Response[v1.DeployResponse], error)
	GetProjectDomain(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetProjectDomainResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.ServiceInfo], error)
	// Deprecated: do not use.
	Delete(context.Context, *connect_go.Request[v1.DeleteRequest]) (*connect_go.Response[v1.DeleteResponse], error)
	Destroy(context.Context, *connect_go.Request[v1.DestroyRequest]) (*connect_go.Response[v1.DestroyResponse], error)
	// Deprecated: do not use.
	Publish(context.Context, *connect_go.Request[v1.PublishRequest]) (*connect_go.Response[emptypb.Empty], error)
	Subscribe(context.Context, *connect_go.Request[v1.SubscribeRequest]) (*connect_go.ServerStreamForClient[v1.SubscribeResponse], error)
	// rpc Promote(google.protobuf.Empty) returns (google.protobuf.Empty);
	GetServices(context.Context, *connect_go.Request[v1.GetServicesRequest]) (*connect_go.Response[v1.GetServicesResponse], error)
	GenerateFiles(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error)
	StartGenerate(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.StartGenerateResponse], error)
	GenerateStatus(context.Context, *connect_go.Request[v1.GenerateStatusRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error)
	Debug(context.Context, *connect_go.Request[v1.DebugRequest]) (*connect_go.Response[v1.DebugResponse], error)
	SignEULA(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	CheckToS(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	// deprecate - change to use *Config functions
	//
	// Deprecated: do not use.
	PutSecret(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error)
	// Deprecated: do not use.
	DeleteSecrets(context.Context, *connect_go.Request[v1.Secrets]) (*connect_go.Response[emptypb.Empty], error)
	// Deprecated: do not use.
	ListSecrets(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.Secrets], error)
	GetConfigs(context.Context, *connect_go.Request[v1.GetConfigsRequest]) (*connect_go.Response[v1.GetConfigsResponse], error)
	PutConfig(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error)
	DeleteConfigs(context.Context, *connect_go.Request[v1.DeleteConfigsRequest]) (*connect_go.Response[emptypb.Empty], error)
	ListConfigs(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.ListConfigsResponse], error)
	PutDeployment(context.Context, *connect_go.Request[v1.PutDeploymentRequest]) (*connect_go.Response[emptypb.Empty], error)
	ListDeployments(context.Context, *connect_go.Request[v1.ListDeploymentsRequest]) (*connect_go.Response[v1.ListDeploymentsResponse], error)
	CreateUploadURL(context.Context, *connect_go.Request[v1.UploadURLRequest]) (*connect_go.Response[v1.UploadURLResponse], error)
	DelegateSubdomainZone(context.Context, *connect_go.Request[v1.DelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error)
	DeleteSubdomainZone(context.Context, *connect_go.Request[v1.DeleteSubdomainZoneRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetDelegateSubdomainZone(context.Context, *connect_go.Request[v1.GetDelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error)
	SetOptions(context.Context, *connect_go.Request[v1.SetOptionsRequest]) (*connect_go.Response[emptypb.Empty], error)
	WhoAmI(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.WhoAmIResponse], error)
	Track(context.Context, *connect_go.Request[v1.TrackRequest]) (*connect_go.Response[emptypb.Empty], error)
	// Endpoint for GDPR compliance
	DeleteMe(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	VerifyDNSSetup(context.Context, *connect_go.Request[v1.VerifyDNSSetupRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetSelectedProvider(context.Context, *connect_go.Request[v1.GetSelectedProviderRequest]) (*connect_go.Response[v1.GetSelectedProviderResponse], error)
	SetSelectedProvider(context.Context, *connect_go.Request[v1.SetSelectedProviderRequest]) (*connect_go.Response[emptypb.Empty], error)
	CanIUse(context.Context, *connect_go.Request[v1.CanIUseRequest]) (*connect_go.Response[v1.CanIUseResponse], error)
	Estimate(context.Context, *connect_go.Request[v1.EstimateRequest]) (*connect_go.Response[v1.EstimateResponse], error)
	Preview(context.Context, *connect_go.Request[v1.PreviewRequest]) (*connect_go.Response[v1.PreviewResponse], error)
	GenerateCompose(context.Context, *connect_go.Request[v1.GenerateComposeRequest]) (*connect_go.Response[v1.GenerateComposeResponse], error)
}

// NewFabricControllerClient constructs a client for the io.defang.v1.FabricController service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFabricControllerClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FabricControllerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &fabricControllerClient{
		getStatus: connect_go.NewClient[emptypb.Empty, v1.Status](
			httpClient,
			baseURL+FabricControllerGetStatusProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		getVersion: connect_go.NewClient[emptypb.Empty, v1.Version](
			httpClient,
			baseURL+FabricControllerGetVersionProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		token: connect_go.NewClient[v1.TokenRequest, v1.TokenResponse](
			httpClient,
			baseURL+FabricControllerTokenProcedure,
			opts...,
		),
		revokeToken: connect_go.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerRevokeTokenProcedure,
			opts...,
		),
		tail: connect_go.NewClient[v1.TailRequest, v1.TailResponse](
			httpClient,
			baseURL+FabricControllerTailProcedure,
			opts...,
		),
		update: connect_go.NewClient[v1.Service, v1.ServiceInfo](
			httpClient,
			baseURL+FabricControllerUpdateProcedure,
			opts...,
		),
		deploy: connect_go.NewClient[v1.DeployRequest, v1.DeployResponse](
			httpClient,
			baseURL+FabricControllerDeployProcedure,
			opts...,
		),
		getProjectDomain: connect_go.NewClient[emptypb.Empty, v1.GetProjectDomainResponse](
			httpClient,
			baseURL+FabricControllerGetProjectDomainProcedure,
			opts...,
		),
		get: connect_go.NewClient[v1.GetRequest, v1.ServiceInfo](
			httpClient,
			baseURL+FabricControllerGetProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		delete: connect_go.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+FabricControllerDeleteProcedure,
			opts...,
		),
		destroy: connect_go.NewClient[v1.DestroyRequest, v1.DestroyResponse](
			httpClient,
			baseURL+FabricControllerDestroyProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		publish: connect_go.NewClient[v1.PublishRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerPublishProcedure,
			opts...,
		),
		subscribe: connect_go.NewClient[v1.SubscribeRequest, v1.SubscribeResponse](
			httpClient,
			baseURL+FabricControllerSubscribeProcedure,
			opts...,
		),
		getServices: connect_go.NewClient[v1.GetServicesRequest, v1.GetServicesResponse](
			httpClient,
			baseURL+FabricControllerGetServicesProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		generateFiles: connect_go.NewClient[v1.GenerateFilesRequest, v1.GenerateFilesResponse](
			httpClient,
			baseURL+FabricControllerGenerateFilesProcedure,
			opts...,
		),
		startGenerate: connect_go.NewClient[v1.GenerateFilesRequest, v1.StartGenerateResponse](
			httpClient,
			baseURL+FabricControllerStartGenerateProcedure,
			opts...,
		),
		generateStatus: connect_go.NewClient[v1.GenerateStatusRequest, v1.GenerateFilesResponse](
			httpClient,
			baseURL+FabricControllerGenerateStatusProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		debug: connect_go.NewClient[v1.DebugRequest, v1.DebugResponse](
			httpClient,
			baseURL+FabricControllerDebugProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		signEULA: connect_go.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerSignEULAProcedure,
			opts...,
		),
		checkToS: connect_go.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerCheckToSProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		putSecret: connect_go.NewClient[v1.PutConfigRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerPutSecretProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		deleteSecrets: connect_go.NewClient[v1.Secrets, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerDeleteSecretsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		listSecrets: connect_go.NewClient[v1.ListConfigsRequest, v1.Secrets](
			httpClient,
			baseURL+FabricControllerListSecretsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		getConfigs: connect_go.NewClient[v1.GetConfigsRequest, v1.GetConfigsResponse](
			httpClient,
			baseURL+FabricControllerGetConfigsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		putConfig: connect_go.NewClient[v1.PutConfigRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerPutConfigProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		deleteConfigs: connect_go.NewClient[v1.DeleteConfigsRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerDeleteConfigsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		listConfigs: connect_go.NewClient[v1.ListConfigsRequest, v1.ListConfigsResponse](
			httpClient,
			baseURL+FabricControllerListConfigsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		putDeployment: connect_go.NewClient[v1.PutDeploymentRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerPutDeploymentProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		listDeployments: connect_go.NewClient[v1.ListDeploymentsRequest, v1.ListDeploymentsResponse](
			httpClient,
			baseURL+FabricControllerListDeploymentsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		createUploadURL: connect_go.NewClient[v1.UploadURLRequest, v1.UploadURLResponse](
			httpClient,
			baseURL+FabricControllerCreateUploadURLProcedure,
			opts...,
		),
		delegateSubdomainZone: connect_go.NewClient[v1.DelegateSubdomainZoneRequest, v1.DelegateSubdomainZoneResponse](
			httpClient,
			baseURL+FabricControllerDelegateSubdomainZoneProcedure,
			opts...,
		),
		deleteSubdomainZone: connect_go.NewClient[v1.DeleteSubdomainZoneRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerDeleteSubdomainZoneProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		getDelegateSubdomainZone: connect_go.NewClient[v1.GetDelegateSubdomainZoneRequest, v1.DelegateSubdomainZoneResponse](
			httpClient,
			baseURL+FabricControllerGetDelegateSubdomainZoneProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		setOptions: connect_go.NewClient[v1.SetOptionsRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerSetOptionsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		whoAmI: connect_go.NewClient[emptypb.Empty, v1.WhoAmIResponse](
			httpClient,
			baseURL+FabricControllerWhoAmIProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		track: connect_go.NewClient[v1.TrackRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerTrackProcedure,
			opts...,
		),
		deleteMe: connect_go.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerDeleteMeProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		verifyDNSSetup: connect_go.NewClient[v1.VerifyDNSSetupRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerVerifyDNSSetupProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		getSelectedProvider: connect_go.NewClient[v1.GetSelectedProviderRequest, v1.GetSelectedProviderResponse](
			httpClient,
			baseURL+FabricControllerGetSelectedProviderProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		setSelectedProvider: connect_go.NewClient[v1.SetSelectedProviderRequest, emptypb.Empty](
			httpClient,
			baseURL+FabricControllerSetSelectedProviderProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
			connect_go.WithClientOptions(opts...),
		),
		canIUse: connect_go.NewClient[v1.CanIUseRequest, v1.CanIUseResponse](
			httpClient,
			baseURL+FabricControllerCanIUseProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		estimate: connect_go.NewClient[v1.EstimateRequest, v1.EstimateResponse](
			httpClient,
			baseURL+FabricControllerEstimateProcedure,
			opts...,
		),
		preview: connect_go.NewClient[v1.PreviewRequest, v1.PreviewResponse](
			httpClient,
			baseURL+FabricControllerPreviewProcedure,
			opts...,
		),
		generateCompose: connect_go.NewClient[v1.GenerateComposeRequest, v1.GenerateComposeResponse](
			httpClient,
			baseURL+FabricControllerGenerateComposeProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
	}
}

// fabricControllerClient implements FabricControllerClient.
type fabricControllerClient struct {
	getStatus                *connect_go.Client[emptypb.Empty, v1.Status]
	getVersion               *connect_go.Client[emptypb.Empty, v1.Version]
	token                    *connect_go.Client[v1.TokenRequest, v1.TokenResponse]
	revokeToken              *connect_go.Client[emptypb.Empty, emptypb.Empty]
	tail                     *connect_go.Client[v1.TailRequest, v1.TailResponse]
	update                   *connect_go.Client[v1.Service, v1.ServiceInfo]
	deploy                   *connect_go.Client[v1.DeployRequest, v1.DeployResponse]
	getProjectDomain         *connect_go.Client[emptypb.Empty, v1.GetProjectDomainResponse]
	get                      *connect_go.Client[v1.GetRequest, v1.ServiceInfo]
	delete                   *connect_go.Client[v1.DeleteRequest, v1.DeleteResponse]
	destroy                  *connect_go.Client[v1.DestroyRequest, v1.DestroyResponse]
	publish                  *connect_go.Client[v1.PublishRequest, emptypb.Empty]
	subscribe                *connect_go.Client[v1.SubscribeRequest, v1.SubscribeResponse]
	getServices              *connect_go.Client[v1.GetServicesRequest, v1.GetServicesResponse]
	generateFiles            *connect_go.Client[v1.GenerateFilesRequest, v1.GenerateFilesResponse]
	startGenerate            *connect_go.Client[v1.GenerateFilesRequest, v1.StartGenerateResponse]
	generateStatus           *connect_go.Client[v1.GenerateStatusRequest, v1.GenerateFilesResponse]
	debug                    *connect_go.Client[v1.DebugRequest, v1.DebugResponse]
	signEULA                 *connect_go.Client[emptypb.Empty, emptypb.Empty]
	checkToS                 *connect_go.Client[emptypb.Empty, emptypb.Empty]
	putSecret                *connect_go.Client[v1.PutConfigRequest, emptypb.Empty]
	deleteSecrets            *connect_go.Client[v1.Secrets, emptypb.Empty]
	listSecrets              *connect_go.Client[v1.ListConfigsRequest, v1.Secrets]
	getConfigs               *connect_go.Client[v1.GetConfigsRequest, v1.GetConfigsResponse]
	putConfig                *connect_go.Client[v1.PutConfigRequest, emptypb.Empty]
	deleteConfigs            *connect_go.Client[v1.DeleteConfigsRequest, emptypb.Empty]
	listConfigs              *connect_go.Client[v1.ListConfigsRequest, v1.ListConfigsResponse]
	putDeployment            *connect_go.Client[v1.PutDeploymentRequest, emptypb.Empty]
	listDeployments          *connect_go.Client[v1.ListDeploymentsRequest, v1.ListDeploymentsResponse]
	createUploadURL          *connect_go.Client[v1.UploadURLRequest, v1.UploadURLResponse]
	delegateSubdomainZone    *connect_go.Client[v1.DelegateSubdomainZoneRequest, v1.DelegateSubdomainZoneResponse]
	deleteSubdomainZone      *connect_go.Client[v1.DeleteSubdomainZoneRequest, emptypb.Empty]
	getDelegateSubdomainZone *connect_go.Client[v1.GetDelegateSubdomainZoneRequest, v1.DelegateSubdomainZoneResponse]
	setOptions               *connect_go.Client[v1.SetOptionsRequest, emptypb.Empty]
	whoAmI                   *connect_go.Client[emptypb.Empty, v1.WhoAmIResponse]
	track                    *connect_go.Client[v1.TrackRequest, emptypb.Empty]
	deleteMe                 *connect_go.Client[emptypb.Empty, emptypb.Empty]
	verifyDNSSetup           *connect_go.Client[v1.VerifyDNSSetupRequest, emptypb.Empty]
	getSelectedProvider      *connect_go.Client[v1.GetSelectedProviderRequest, v1.GetSelectedProviderResponse]
	setSelectedProvider      *connect_go.Client[v1.SetSelectedProviderRequest, emptypb.Empty]
	canIUse                  *connect_go.Client[v1.CanIUseRequest, v1.CanIUseResponse]
	estimate                 *connect_go.Client[v1.EstimateRequest, v1.EstimateResponse]
	preview                  *connect_go.Client[v1.PreviewRequest, v1.PreviewResponse]
	generateCompose          *connect_go.Client[v1.GenerateComposeRequest, v1.GenerateComposeResponse]
}

// GetStatus calls io.defang.v1.FabricController.GetStatus.
func (c *fabricControllerClient) GetStatus(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Status], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// GetVersion calls io.defang.v1.FabricController.GetVersion.
func (c *fabricControllerClient) GetVersion(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Version], error) {
	return c.getVersion.CallUnary(ctx, req)
}

// Token calls io.defang.v1.FabricController.Token.
func (c *fabricControllerClient) Token(ctx context.Context, req *connect_go.Request[v1.TokenRequest]) (*connect_go.Response[v1.TokenResponse], error) {
	return c.token.CallUnary(ctx, req)
}

// RevokeToken calls io.defang.v1.FabricController.RevokeToken.
func (c *fabricControllerClient) RevokeToken(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// Tail calls io.defang.v1.FabricController.Tail.
func (c *fabricControllerClient) Tail(ctx context.Context, req *connect_go.Request[v1.TailRequest]) (*connect_go.ServerStreamForClient[v1.TailResponse], error) {
	return c.tail.CallServerStream(ctx, req)
}

// Update calls io.defang.v1.FabricController.Update.
//
// Deprecated: do not use.
func (c *fabricControllerClient) Update(ctx context.Context, req *connect_go.Request[v1.Service]) (*connect_go.Response[v1.ServiceInfo], error) {
	return c.update.CallUnary(ctx, req)
}

// Deploy calls io.defang.v1.FabricController.Deploy.
func (c *fabricControllerClient) Deploy(ctx context.Context, req *connect_go.Request[v1.DeployRequest]) (*connect_go.Response[v1.DeployResponse], error) {
	return c.deploy.CallUnary(ctx, req)
}

// GetProjectDomain calls io.defang.v1.FabricController.GetProjectDomain.
func (c *fabricControllerClient) GetProjectDomain(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetProjectDomainResponse], error) {
	return c.getProjectDomain.CallUnary(ctx, req)
}

// Get calls io.defang.v1.FabricController.Get.
func (c *fabricControllerClient) Get(ctx context.Context, req *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.ServiceInfo], error) {
	return c.get.CallUnary(ctx, req)
}

// Delete calls io.defang.v1.FabricController.Delete.
//
// Deprecated: do not use.
func (c *fabricControllerClient) Delete(ctx context.Context, req *connect_go.Request[v1.DeleteRequest]) (*connect_go.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Destroy calls io.defang.v1.FabricController.Destroy.
func (c *fabricControllerClient) Destroy(ctx context.Context, req *connect_go.Request[v1.DestroyRequest]) (*connect_go.Response[v1.DestroyResponse], error) {
	return c.destroy.CallUnary(ctx, req)
}

// Publish calls io.defang.v1.FabricController.Publish.
//
// Deprecated: do not use.
func (c *fabricControllerClient) Publish(ctx context.Context, req *connect_go.Request[v1.PublishRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.publish.CallUnary(ctx, req)
}

// Subscribe calls io.defang.v1.FabricController.Subscribe.
func (c *fabricControllerClient) Subscribe(ctx context.Context, req *connect_go.Request[v1.SubscribeRequest]) (*connect_go.ServerStreamForClient[v1.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// GetServices calls io.defang.v1.FabricController.GetServices.
func (c *fabricControllerClient) GetServices(ctx context.Context, req *connect_go.Request[v1.GetServicesRequest]) (*connect_go.Response[v1.GetServicesResponse], error) {
	return c.getServices.CallUnary(ctx, req)
}

// GenerateFiles calls io.defang.v1.FabricController.GenerateFiles.
func (c *fabricControllerClient) GenerateFiles(ctx context.Context, req *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error) {
	return c.generateFiles.CallUnary(ctx, req)
}

// StartGenerate calls io.defang.v1.FabricController.StartGenerate.
func (c *fabricControllerClient) StartGenerate(ctx context.Context, req *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.StartGenerateResponse], error) {
	return c.startGenerate.CallUnary(ctx, req)
}

// GenerateStatus calls io.defang.v1.FabricController.GenerateStatus.
func (c *fabricControllerClient) GenerateStatus(ctx context.Context, req *connect_go.Request[v1.GenerateStatusRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error) {
	return c.generateStatus.CallUnary(ctx, req)
}

// Debug calls io.defang.v1.FabricController.Debug.
func (c *fabricControllerClient) Debug(ctx context.Context, req *connect_go.Request[v1.DebugRequest]) (*connect_go.Response[v1.DebugResponse], error) {
	return c.debug.CallUnary(ctx, req)
}

// SignEULA calls io.defang.v1.FabricController.SignEULA.
func (c *fabricControllerClient) SignEULA(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return c.signEULA.CallUnary(ctx, req)
}

// CheckToS calls io.defang.v1.FabricController.CheckToS.
func (c *fabricControllerClient) CheckToS(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return c.checkToS.CallUnary(ctx, req)
}

// PutSecret calls io.defang.v1.FabricController.PutSecret.
//
// Deprecated: do not use.
func (c *fabricControllerClient) PutSecret(ctx context.Context, req *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.putSecret.CallUnary(ctx, req)
}

// DeleteSecrets calls io.defang.v1.FabricController.DeleteSecrets.
//
// Deprecated: do not use.
func (c *fabricControllerClient) DeleteSecrets(ctx context.Context, req *connect_go.Request[v1.Secrets]) (*connect_go.Response[emptypb.Empty], error) {
	return c.deleteSecrets.CallUnary(ctx, req)
}

// ListSecrets calls io.defang.v1.FabricController.ListSecrets.
//
// Deprecated: do not use.
func (c *fabricControllerClient) ListSecrets(ctx context.Context, req *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.Secrets], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// GetConfigs calls io.defang.v1.FabricController.GetConfigs.
func (c *fabricControllerClient) GetConfigs(ctx context.Context, req *connect_go.Request[v1.GetConfigsRequest]) (*connect_go.Response[v1.GetConfigsResponse], error) {
	return c.getConfigs.CallUnary(ctx, req)
}

// PutConfig calls io.defang.v1.FabricController.PutConfig.
func (c *fabricControllerClient) PutConfig(ctx context.Context, req *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.putConfig.CallUnary(ctx, req)
}

// DeleteConfigs calls io.defang.v1.FabricController.DeleteConfigs.
func (c *fabricControllerClient) DeleteConfigs(ctx context.Context, req *connect_go.Request[v1.DeleteConfigsRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.deleteConfigs.CallUnary(ctx, req)
}

// ListConfigs calls io.defang.v1.FabricController.ListConfigs.
func (c *fabricControllerClient) ListConfigs(ctx context.Context, req *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.ListConfigsResponse], error) {
	return c.listConfigs.CallUnary(ctx, req)
}

// PutDeployment calls io.defang.v1.FabricController.PutDeployment.
func (c *fabricControllerClient) PutDeployment(ctx context.Context, req *connect_go.Request[v1.PutDeploymentRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.putDeployment.CallUnary(ctx, req)
}

// ListDeployments calls io.defang.v1.FabricController.ListDeployments.
func (c *fabricControllerClient) ListDeployments(ctx context.Context, req *connect_go.Request[v1.ListDeploymentsRequest]) (*connect_go.Response[v1.ListDeploymentsResponse], error) {
	return c.listDeployments.CallUnary(ctx, req)
}

// CreateUploadURL calls io.defang.v1.FabricController.CreateUploadURL.
func (c *fabricControllerClient) CreateUploadURL(ctx context.Context, req *connect_go.Request[v1.UploadURLRequest]) (*connect_go.Response[v1.UploadURLResponse], error) {
	return c.createUploadURL.CallUnary(ctx, req)
}

// DelegateSubdomainZone calls io.defang.v1.FabricController.DelegateSubdomainZone.
func (c *fabricControllerClient) DelegateSubdomainZone(ctx context.Context, req *connect_go.Request[v1.DelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error) {
	return c.delegateSubdomainZone.CallUnary(ctx, req)
}

// DeleteSubdomainZone calls io.defang.v1.FabricController.DeleteSubdomainZone.
func (c *fabricControllerClient) DeleteSubdomainZone(ctx context.Context, req *connect_go.Request[v1.DeleteSubdomainZoneRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.deleteSubdomainZone.CallUnary(ctx, req)
}

// GetDelegateSubdomainZone calls io.defang.v1.FabricController.GetDelegateSubdomainZone.
func (c *fabricControllerClient) GetDelegateSubdomainZone(ctx context.Context, req *connect_go.Request[v1.GetDelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error) {
	return c.getDelegateSubdomainZone.CallUnary(ctx, req)
}

// SetOptions calls io.defang.v1.FabricController.SetOptions.
func (c *fabricControllerClient) SetOptions(ctx context.Context, req *connect_go.Request[v1.SetOptionsRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.setOptions.CallUnary(ctx, req)
}

// WhoAmI calls io.defang.v1.FabricController.WhoAmI.
func (c *fabricControllerClient) WhoAmI(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.WhoAmIResponse], error) {
	return c.whoAmI.CallUnary(ctx, req)
}

// Track calls io.defang.v1.FabricController.Track.
func (c *fabricControllerClient) Track(ctx context.Context, req *connect_go.Request[v1.TrackRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.track.CallUnary(ctx, req)
}

// DeleteMe calls io.defang.v1.FabricController.DeleteMe.
func (c *fabricControllerClient) DeleteMe(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return c.deleteMe.CallUnary(ctx, req)
}

// VerifyDNSSetup calls io.defang.v1.FabricController.VerifyDNSSetup.
func (c *fabricControllerClient) VerifyDNSSetup(ctx context.Context, req *connect_go.Request[v1.VerifyDNSSetupRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.verifyDNSSetup.CallUnary(ctx, req)
}

// GetSelectedProvider calls io.defang.v1.FabricController.GetSelectedProvider.
func (c *fabricControllerClient) GetSelectedProvider(ctx context.Context, req *connect_go.Request[v1.GetSelectedProviderRequest]) (*connect_go.Response[v1.GetSelectedProviderResponse], error) {
	return c.getSelectedProvider.CallUnary(ctx, req)
}

// SetSelectedProvider calls io.defang.v1.FabricController.SetSelectedProvider.
func (c *fabricControllerClient) SetSelectedProvider(ctx context.Context, req *connect_go.Request[v1.SetSelectedProviderRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.setSelectedProvider.CallUnary(ctx, req)
}

// CanIUse calls io.defang.v1.FabricController.CanIUse.
func (c *fabricControllerClient) CanIUse(ctx context.Context, req *connect_go.Request[v1.CanIUseRequest]) (*connect_go.Response[v1.CanIUseResponse], error) {
	return c.canIUse.CallUnary(ctx, req)
}

// Estimate calls io.defang.v1.FabricController.Estimate.
func (c *fabricControllerClient) Estimate(ctx context.Context, req *connect_go.Request[v1.EstimateRequest]) (*connect_go.Response[v1.EstimateResponse], error) {
	return c.estimate.CallUnary(ctx, req)
}

// Preview calls io.defang.v1.FabricController.Preview.
func (c *fabricControllerClient) Preview(ctx context.Context, req *connect_go.Request[v1.PreviewRequest]) (*connect_go.Response[v1.PreviewResponse], error) {
	return c.preview.CallUnary(ctx, req)
}

// GenerateCompose calls io.defang.v1.FabricController.GenerateCompose.
func (c *fabricControllerClient) GenerateCompose(ctx context.Context, req *connect_go.Request[v1.GenerateComposeRequest]) (*connect_go.Response[v1.GenerateComposeResponse], error) {
	return c.generateCompose.CallUnary(ctx, req)
}

// FabricControllerHandler is an implementation of the io.defang.v1.FabricController service.
type FabricControllerHandler interface {
	GetStatus(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Status], error)
	GetVersion(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Version], error)
	Token(context.Context, *connect_go.Request[v1.TokenRequest]) (*connect_go.Response[v1.TokenResponse], error)
	RevokeToken(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	Tail(context.Context, *connect_go.Request[v1.TailRequest], *connect_go.ServerStream[v1.TailResponse]) error
	// Deprecated: do not use.
	Update(context.Context, *connect_go.Request[v1.Service]) (*connect_go.Response[v1.ServiceInfo], error)
	Deploy(context.Context, *connect_go.Request[v1.DeployRequest]) (*connect_go.Response[v1.DeployResponse], error)
	GetProjectDomain(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetProjectDomainResponse], error)
	Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.ServiceInfo], error)
	// Deprecated: do not use.
	Delete(context.Context, *connect_go.Request[v1.DeleteRequest]) (*connect_go.Response[v1.DeleteResponse], error)
	Destroy(context.Context, *connect_go.Request[v1.DestroyRequest]) (*connect_go.Response[v1.DestroyResponse], error)
	// Deprecated: do not use.
	Publish(context.Context, *connect_go.Request[v1.PublishRequest]) (*connect_go.Response[emptypb.Empty], error)
	Subscribe(context.Context, *connect_go.Request[v1.SubscribeRequest], *connect_go.ServerStream[v1.SubscribeResponse]) error
	// rpc Promote(google.protobuf.Empty) returns (google.protobuf.Empty);
	GetServices(context.Context, *connect_go.Request[v1.GetServicesRequest]) (*connect_go.Response[v1.GetServicesResponse], error)
	GenerateFiles(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error)
	StartGenerate(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.StartGenerateResponse], error)
	GenerateStatus(context.Context, *connect_go.Request[v1.GenerateStatusRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error)
	Debug(context.Context, *connect_go.Request[v1.DebugRequest]) (*connect_go.Response[v1.DebugResponse], error)
	SignEULA(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	CheckToS(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	// deprecate - change to use *Config functions
	//
	// Deprecated: do not use.
	PutSecret(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error)
	// Deprecated: do not use.
	DeleteSecrets(context.Context, *connect_go.Request[v1.Secrets]) (*connect_go.Response[emptypb.Empty], error)
	// Deprecated: do not use.
	ListSecrets(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.Secrets], error)
	GetConfigs(context.Context, *connect_go.Request[v1.GetConfigsRequest]) (*connect_go.Response[v1.GetConfigsResponse], error)
	PutConfig(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error)
	DeleteConfigs(context.Context, *connect_go.Request[v1.DeleteConfigsRequest]) (*connect_go.Response[emptypb.Empty], error)
	ListConfigs(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.ListConfigsResponse], error)
	PutDeployment(context.Context, *connect_go.Request[v1.PutDeploymentRequest]) (*connect_go.Response[emptypb.Empty], error)
	ListDeployments(context.Context, *connect_go.Request[v1.ListDeploymentsRequest]) (*connect_go.Response[v1.ListDeploymentsResponse], error)
	CreateUploadURL(context.Context, *connect_go.Request[v1.UploadURLRequest]) (*connect_go.Response[v1.UploadURLResponse], error)
	DelegateSubdomainZone(context.Context, *connect_go.Request[v1.DelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error)
	DeleteSubdomainZone(context.Context, *connect_go.Request[v1.DeleteSubdomainZoneRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetDelegateSubdomainZone(context.Context, *connect_go.Request[v1.GetDelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error)
	SetOptions(context.Context, *connect_go.Request[v1.SetOptionsRequest]) (*connect_go.Response[emptypb.Empty], error)
	WhoAmI(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.WhoAmIResponse], error)
	Track(context.Context, *connect_go.Request[v1.TrackRequest]) (*connect_go.Response[emptypb.Empty], error)
	// Endpoint for GDPR compliance
	DeleteMe(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error)
	VerifyDNSSetup(context.Context, *connect_go.Request[v1.VerifyDNSSetupRequest]) (*connect_go.Response[emptypb.Empty], error)
	GetSelectedProvider(context.Context, *connect_go.Request[v1.GetSelectedProviderRequest]) (*connect_go.Response[v1.GetSelectedProviderResponse], error)
	SetSelectedProvider(context.Context, *connect_go.Request[v1.SetSelectedProviderRequest]) (*connect_go.Response[emptypb.Empty], error)
	CanIUse(context.Context, *connect_go.Request[v1.CanIUseRequest]) (*connect_go.Response[v1.CanIUseResponse], error)
	Estimate(context.Context, *connect_go.Request[v1.EstimateRequest]) (*connect_go.Response[v1.EstimateResponse], error)
	Preview(context.Context, *connect_go.Request[v1.PreviewRequest]) (*connect_go.Response[v1.PreviewResponse], error)
	GenerateCompose(context.Context, *connect_go.Request[v1.GenerateComposeRequest]) (*connect_go.Response[v1.GenerateComposeResponse], error)
}

// NewFabricControllerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFabricControllerHandler(svc FabricControllerHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	fabricControllerGetStatusHandler := connect_go.NewUnaryHandler(
		FabricControllerGetStatusProcedure,
		svc.GetStatus,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerGetVersionHandler := connect_go.NewUnaryHandler(
		FabricControllerGetVersionProcedure,
		svc.GetVersion,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerTokenHandler := connect_go.NewUnaryHandler(
		FabricControllerTokenProcedure,
		svc.Token,
		opts...,
	)
	fabricControllerRevokeTokenHandler := connect_go.NewUnaryHandler(
		FabricControllerRevokeTokenProcedure,
		svc.RevokeToken,
		opts...,
	)
	fabricControllerTailHandler := connect_go.NewServerStreamHandler(
		FabricControllerTailProcedure,
		svc.Tail,
		opts...,
	)
	fabricControllerUpdateHandler := connect_go.NewUnaryHandler(
		FabricControllerUpdateProcedure,
		svc.Update,
		opts...,
	)
	fabricControllerDeployHandler := connect_go.NewUnaryHandler(
		FabricControllerDeployProcedure,
		svc.Deploy,
		opts...,
	)
	fabricControllerGetProjectDomainHandler := connect_go.NewUnaryHandler(
		FabricControllerGetProjectDomainProcedure,
		svc.GetProjectDomain,
		opts...,
	)
	fabricControllerGetHandler := connect_go.NewUnaryHandler(
		FabricControllerGetProcedure,
		svc.Get,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerDeleteHandler := connect_go.NewUnaryHandler(
		FabricControllerDeleteProcedure,
		svc.Delete,
		opts...,
	)
	fabricControllerDestroyHandler := connect_go.NewUnaryHandler(
		FabricControllerDestroyProcedure,
		svc.Destroy,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerPublishHandler := connect_go.NewUnaryHandler(
		FabricControllerPublishProcedure,
		svc.Publish,
		opts...,
	)
	fabricControllerSubscribeHandler := connect_go.NewServerStreamHandler(
		FabricControllerSubscribeProcedure,
		svc.Subscribe,
		opts...,
	)
	fabricControllerGetServicesHandler := connect_go.NewUnaryHandler(
		FabricControllerGetServicesProcedure,
		svc.GetServices,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerGenerateFilesHandler := connect_go.NewUnaryHandler(
		FabricControllerGenerateFilesProcedure,
		svc.GenerateFiles,
		opts...,
	)
	fabricControllerStartGenerateHandler := connect_go.NewUnaryHandler(
		FabricControllerStartGenerateProcedure,
		svc.StartGenerate,
		opts...,
	)
	fabricControllerGenerateStatusHandler := connect_go.NewUnaryHandler(
		FabricControllerGenerateStatusProcedure,
		svc.GenerateStatus,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerDebugHandler := connect_go.NewUnaryHandler(
		FabricControllerDebugProcedure,
		svc.Debug,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerSignEULAHandler := connect_go.NewUnaryHandler(
		FabricControllerSignEULAProcedure,
		svc.SignEULA,
		opts...,
	)
	fabricControllerCheckToSHandler := connect_go.NewUnaryHandler(
		FabricControllerCheckToSProcedure,
		svc.CheckToS,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerPutSecretHandler := connect_go.NewUnaryHandler(
		FabricControllerPutSecretProcedure,
		svc.PutSecret,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerDeleteSecretsHandler := connect_go.NewUnaryHandler(
		FabricControllerDeleteSecretsProcedure,
		svc.DeleteSecrets,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerListSecretsHandler := connect_go.NewUnaryHandler(
		FabricControllerListSecretsProcedure,
		svc.ListSecrets,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerGetConfigsHandler := connect_go.NewUnaryHandler(
		FabricControllerGetConfigsProcedure,
		svc.GetConfigs,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerPutConfigHandler := connect_go.NewUnaryHandler(
		FabricControllerPutConfigProcedure,
		svc.PutConfig,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerDeleteConfigsHandler := connect_go.NewUnaryHandler(
		FabricControllerDeleteConfigsProcedure,
		svc.DeleteConfigs,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerListConfigsHandler := connect_go.NewUnaryHandler(
		FabricControllerListConfigsProcedure,
		svc.ListConfigs,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerPutDeploymentHandler := connect_go.NewUnaryHandler(
		FabricControllerPutDeploymentProcedure,
		svc.PutDeployment,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerListDeploymentsHandler := connect_go.NewUnaryHandler(
		FabricControllerListDeploymentsProcedure,
		svc.ListDeployments,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerCreateUploadURLHandler := connect_go.NewUnaryHandler(
		FabricControllerCreateUploadURLProcedure,
		svc.CreateUploadURL,
		opts...,
	)
	fabricControllerDelegateSubdomainZoneHandler := connect_go.NewUnaryHandler(
		FabricControllerDelegateSubdomainZoneProcedure,
		svc.DelegateSubdomainZone,
		opts...,
	)
	fabricControllerDeleteSubdomainZoneHandler := connect_go.NewUnaryHandler(
		FabricControllerDeleteSubdomainZoneProcedure,
		svc.DeleteSubdomainZone,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerGetDelegateSubdomainZoneHandler := connect_go.NewUnaryHandler(
		FabricControllerGetDelegateSubdomainZoneProcedure,
		svc.GetDelegateSubdomainZone,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerSetOptionsHandler := connect_go.NewUnaryHandler(
		FabricControllerSetOptionsProcedure,
		svc.SetOptions,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerWhoAmIHandler := connect_go.NewUnaryHandler(
		FabricControllerWhoAmIProcedure,
		svc.WhoAmI,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerTrackHandler := connect_go.NewUnaryHandler(
		FabricControllerTrackProcedure,
		svc.Track,
		opts...,
	)
	fabricControllerDeleteMeHandler := connect_go.NewUnaryHandler(
		FabricControllerDeleteMeProcedure,
		svc.DeleteMe,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerVerifyDNSSetupHandler := connect_go.NewUnaryHandler(
		FabricControllerVerifyDNSSetupProcedure,
		svc.VerifyDNSSetup,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerGetSelectedProviderHandler := connect_go.NewUnaryHandler(
		FabricControllerGetSelectedProviderProcedure,
		svc.GetSelectedProvider,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerSetSelectedProviderHandler := connect_go.NewUnaryHandler(
		FabricControllerSetSelectedProviderProcedure,
		svc.SetSelectedProvider,
		connect_go.WithIdempotency(connect_go.IdempotencyIdempotent),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerCanIUseHandler := connect_go.NewUnaryHandler(
		FabricControllerCanIUseProcedure,
		svc.CanIUse,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	fabricControllerEstimateHandler := connect_go.NewUnaryHandler(
		FabricControllerEstimateProcedure,
		svc.Estimate,
		opts...,
	)
	fabricControllerPreviewHandler := connect_go.NewUnaryHandler(
		FabricControllerPreviewProcedure,
		svc.Preview,
		opts...,
	)
	fabricControllerGenerateComposeHandler := connect_go.NewUnaryHandler(
		FabricControllerGenerateComposeProcedure,
		svc.GenerateCompose,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	return "/io.defang.v1.FabricController/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FabricControllerGetStatusProcedure:
			fabricControllerGetStatusHandler.ServeHTTP(w, r)
		case FabricControllerGetVersionProcedure:
			fabricControllerGetVersionHandler.ServeHTTP(w, r)
		case FabricControllerTokenProcedure:
			fabricControllerTokenHandler.ServeHTTP(w, r)
		case FabricControllerRevokeTokenProcedure:
			fabricControllerRevokeTokenHandler.ServeHTTP(w, r)
		case FabricControllerTailProcedure:
			fabricControllerTailHandler.ServeHTTP(w, r)
		case FabricControllerUpdateProcedure:
			fabricControllerUpdateHandler.ServeHTTP(w, r)
		case FabricControllerDeployProcedure:
			fabricControllerDeployHandler.ServeHTTP(w, r)
		case FabricControllerGetProjectDomainProcedure:
			fabricControllerGetProjectDomainHandler.ServeHTTP(w, r)
		case FabricControllerGetProcedure:
			fabricControllerGetHandler.ServeHTTP(w, r)
		case FabricControllerDeleteProcedure:
			fabricControllerDeleteHandler.ServeHTTP(w, r)
		case FabricControllerDestroyProcedure:
			fabricControllerDestroyHandler.ServeHTTP(w, r)
		case FabricControllerPublishProcedure:
			fabricControllerPublishHandler.ServeHTTP(w, r)
		case FabricControllerSubscribeProcedure:
			fabricControllerSubscribeHandler.ServeHTTP(w, r)
		case FabricControllerGetServicesProcedure:
			fabricControllerGetServicesHandler.ServeHTTP(w, r)
		case FabricControllerGenerateFilesProcedure:
			fabricControllerGenerateFilesHandler.ServeHTTP(w, r)
		case FabricControllerStartGenerateProcedure:
			fabricControllerStartGenerateHandler.ServeHTTP(w, r)
		case FabricControllerGenerateStatusProcedure:
			fabricControllerGenerateStatusHandler.ServeHTTP(w, r)
		case FabricControllerDebugProcedure:
			fabricControllerDebugHandler.ServeHTTP(w, r)
		case FabricControllerSignEULAProcedure:
			fabricControllerSignEULAHandler.ServeHTTP(w, r)
		case FabricControllerCheckToSProcedure:
			fabricControllerCheckToSHandler.ServeHTTP(w, r)
		case FabricControllerPutSecretProcedure:
			fabricControllerPutSecretHandler.ServeHTTP(w, r)
		case FabricControllerDeleteSecretsProcedure:
			fabricControllerDeleteSecretsHandler.ServeHTTP(w, r)
		case FabricControllerListSecretsProcedure:
			fabricControllerListSecretsHandler.ServeHTTP(w, r)
		case FabricControllerGetConfigsProcedure:
			fabricControllerGetConfigsHandler.ServeHTTP(w, r)
		case FabricControllerPutConfigProcedure:
			fabricControllerPutConfigHandler.ServeHTTP(w, r)
		case FabricControllerDeleteConfigsProcedure:
			fabricControllerDeleteConfigsHandler.ServeHTTP(w, r)
		case FabricControllerListConfigsProcedure:
			fabricControllerListConfigsHandler.ServeHTTP(w, r)
		case FabricControllerPutDeploymentProcedure:
			fabricControllerPutDeploymentHandler.ServeHTTP(w, r)
		case FabricControllerListDeploymentsProcedure:
			fabricControllerListDeploymentsHandler.ServeHTTP(w, r)
		case FabricControllerCreateUploadURLProcedure:
			fabricControllerCreateUploadURLHandler.ServeHTTP(w, r)
		case FabricControllerDelegateSubdomainZoneProcedure:
			fabricControllerDelegateSubdomainZoneHandler.ServeHTTP(w, r)
		case FabricControllerDeleteSubdomainZoneProcedure:
			fabricControllerDeleteSubdomainZoneHandler.ServeHTTP(w, r)
		case FabricControllerGetDelegateSubdomainZoneProcedure:
			fabricControllerGetDelegateSubdomainZoneHandler.ServeHTTP(w, r)
		case FabricControllerSetOptionsProcedure:
			fabricControllerSetOptionsHandler.ServeHTTP(w, r)
		case FabricControllerWhoAmIProcedure:
			fabricControllerWhoAmIHandler.ServeHTTP(w, r)
		case FabricControllerTrackProcedure:
			fabricControllerTrackHandler.ServeHTTP(w, r)
		case FabricControllerDeleteMeProcedure:
			fabricControllerDeleteMeHandler.ServeHTTP(w, r)
		case FabricControllerVerifyDNSSetupProcedure:
			fabricControllerVerifyDNSSetupHandler.ServeHTTP(w, r)
		case FabricControllerGetSelectedProviderProcedure:
			fabricControllerGetSelectedProviderHandler.ServeHTTP(w, r)
		case FabricControllerSetSelectedProviderProcedure:
			fabricControllerSetSelectedProviderHandler.ServeHTTP(w, r)
		case FabricControllerCanIUseProcedure:
			fabricControllerCanIUseHandler.ServeHTTP(w, r)
		case FabricControllerEstimateProcedure:
			fabricControllerEstimateHandler.ServeHTTP(w, r)
		case FabricControllerPreviewProcedure:
			fabricControllerPreviewHandler.ServeHTTP(w, r)
		case FabricControllerGenerateComposeProcedure:
			fabricControllerGenerateComposeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFabricControllerHandler returns CodeUnimplemented from all methods.
type UnimplementedFabricControllerHandler struct{}

func (UnimplementedFabricControllerHandler) GetStatus(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Status], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetStatus is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetVersion(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.Version], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetVersion is not implemented"))
}

func (UnimplementedFabricControllerHandler) Token(context.Context, *connect_go.Request[v1.TokenRequest]) (*connect_go.Response[v1.TokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Token is not implemented"))
}

func (UnimplementedFabricControllerHandler) RevokeToken(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.RevokeToken is not implemented"))
}

func (UnimplementedFabricControllerHandler) Tail(context.Context, *connect_go.Request[v1.TailRequest], *connect_go.ServerStream[v1.TailResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Tail is not implemented"))
}

func (UnimplementedFabricControllerHandler) Update(context.Context, *connect_go.Request[v1.Service]) (*connect_go.Response[v1.ServiceInfo], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Update is not implemented"))
}

func (UnimplementedFabricControllerHandler) Deploy(context.Context, *connect_go.Request[v1.DeployRequest]) (*connect_go.Response[v1.DeployResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Deploy is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetProjectDomain(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetProjectDomainResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetProjectDomain is not implemented"))
}

func (UnimplementedFabricControllerHandler) Get(context.Context, *connect_go.Request[v1.GetRequest]) (*connect_go.Response[v1.ServiceInfo], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Get is not implemented"))
}

func (UnimplementedFabricControllerHandler) Delete(context.Context, *connect_go.Request[v1.DeleteRequest]) (*connect_go.Response[v1.DeleteResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Delete is not implemented"))
}

func (UnimplementedFabricControllerHandler) Destroy(context.Context, *connect_go.Request[v1.DestroyRequest]) (*connect_go.Response[v1.DestroyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Destroy is not implemented"))
}

func (UnimplementedFabricControllerHandler) Publish(context.Context, *connect_go.Request[v1.PublishRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Publish is not implemented"))
}

func (UnimplementedFabricControllerHandler) Subscribe(context.Context, *connect_go.Request[v1.SubscribeRequest], *connect_go.ServerStream[v1.SubscribeResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Subscribe is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetServices(context.Context, *connect_go.Request[v1.GetServicesRequest]) (*connect_go.Response[v1.GetServicesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetServices is not implemented"))
}

func (UnimplementedFabricControllerHandler) GenerateFiles(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GenerateFiles is not implemented"))
}

func (UnimplementedFabricControllerHandler) StartGenerate(context.Context, *connect_go.Request[v1.GenerateFilesRequest]) (*connect_go.Response[v1.StartGenerateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.StartGenerate is not implemented"))
}

func (UnimplementedFabricControllerHandler) GenerateStatus(context.Context, *connect_go.Request[v1.GenerateStatusRequest]) (*connect_go.Response[v1.GenerateFilesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GenerateStatus is not implemented"))
}

func (UnimplementedFabricControllerHandler) Debug(context.Context, *connect_go.Request[v1.DebugRequest]) (*connect_go.Response[v1.DebugResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Debug is not implemented"))
}

func (UnimplementedFabricControllerHandler) SignEULA(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.SignEULA is not implemented"))
}

func (UnimplementedFabricControllerHandler) CheckToS(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.CheckToS is not implemented"))
}

func (UnimplementedFabricControllerHandler) PutSecret(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.PutSecret is not implemented"))
}

func (UnimplementedFabricControllerHandler) DeleteSecrets(context.Context, *connect_go.Request[v1.Secrets]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.DeleteSecrets is not implemented"))
}

func (UnimplementedFabricControllerHandler) ListSecrets(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.Secrets], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.ListSecrets is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetConfigs(context.Context, *connect_go.Request[v1.GetConfigsRequest]) (*connect_go.Response[v1.GetConfigsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetConfigs is not implemented"))
}

func (UnimplementedFabricControllerHandler) PutConfig(context.Context, *connect_go.Request[v1.PutConfigRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.PutConfig is not implemented"))
}

func (UnimplementedFabricControllerHandler) DeleteConfigs(context.Context, *connect_go.Request[v1.DeleteConfigsRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.DeleteConfigs is not implemented"))
}

func (UnimplementedFabricControllerHandler) ListConfigs(context.Context, *connect_go.Request[v1.ListConfigsRequest]) (*connect_go.Response[v1.ListConfigsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.ListConfigs is not implemented"))
}

func (UnimplementedFabricControllerHandler) PutDeployment(context.Context, *connect_go.Request[v1.PutDeploymentRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.PutDeployment is not implemented"))
}

func (UnimplementedFabricControllerHandler) ListDeployments(context.Context, *connect_go.Request[v1.ListDeploymentsRequest]) (*connect_go.Response[v1.ListDeploymentsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.ListDeployments is not implemented"))
}

func (UnimplementedFabricControllerHandler) CreateUploadURL(context.Context, *connect_go.Request[v1.UploadURLRequest]) (*connect_go.Response[v1.UploadURLResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.CreateUploadURL is not implemented"))
}

func (UnimplementedFabricControllerHandler) DelegateSubdomainZone(context.Context, *connect_go.Request[v1.DelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.DelegateSubdomainZone is not implemented"))
}

func (UnimplementedFabricControllerHandler) DeleteSubdomainZone(context.Context, *connect_go.Request[v1.DeleteSubdomainZoneRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.DeleteSubdomainZone is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetDelegateSubdomainZone(context.Context, *connect_go.Request[v1.GetDelegateSubdomainZoneRequest]) (*connect_go.Response[v1.DelegateSubdomainZoneResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetDelegateSubdomainZone is not implemented"))
}

func (UnimplementedFabricControllerHandler) SetOptions(context.Context, *connect_go.Request[v1.SetOptionsRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.SetOptions is not implemented"))
}

func (UnimplementedFabricControllerHandler) WhoAmI(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.WhoAmIResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.WhoAmI is not implemented"))
}

func (UnimplementedFabricControllerHandler) Track(context.Context, *connect_go.Request[v1.TrackRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Track is not implemented"))
}

func (UnimplementedFabricControllerHandler) DeleteMe(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.DeleteMe is not implemented"))
}

func (UnimplementedFabricControllerHandler) VerifyDNSSetup(context.Context, *connect_go.Request[v1.VerifyDNSSetupRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.VerifyDNSSetup is not implemented"))
}

func (UnimplementedFabricControllerHandler) GetSelectedProvider(context.Context, *connect_go.Request[v1.GetSelectedProviderRequest]) (*connect_go.Response[v1.GetSelectedProviderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GetSelectedProvider is not implemented"))
}

func (UnimplementedFabricControllerHandler) SetSelectedProvider(context.Context, *connect_go.Request[v1.SetSelectedProviderRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.SetSelectedProvider is not implemented"))
}

func (UnimplementedFabricControllerHandler) CanIUse(context.Context, *connect_go.Request[v1.CanIUseRequest]) (*connect_go.Response[v1.CanIUseResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.CanIUse is not implemented"))
}

func (UnimplementedFabricControllerHandler) Estimate(context.Context, *connect_go.Request[v1.EstimateRequest]) (*connect_go.Response[v1.EstimateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Estimate is not implemented"))
}

func (UnimplementedFabricControllerHandler) Preview(context.Context, *connect_go.Request[v1.PreviewRequest]) (*connect_go.Response[v1.PreviewResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.Preview is not implemented"))
}

func (UnimplementedFabricControllerHandler) GenerateCompose(context.Context, *connect_go.Request[v1.GenerateComposeRequest]) (*connect_go.Response[v1.GenerateComposeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("io.defang.v1.FabricController.GenerateCompose is not implemented"))
}
