version: '3.9'
services:
  service1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
    deploy:
      resources:
        reservations:
          memory: 50M
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
