version: '3.9'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
    secrets:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
secrets:
  AWS_ACCESS_KEY:
    external: true
  AWS_SECRET_KEY:
    external: true
