version: '3.9'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    secrets:
      - OPENAI_KEY
secrets:
  OPENAI_KEY:
    external: true
