version: '3.9'
services:
  service1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
    environment:
      - OPENAI_KEY
    deploy:
      resources:
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]
