version: '3.9'
services:
  gpu-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
      shm_size: 30G
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '2.0'
          memory: 8192M
          devices:
            - capabilities: ["gpu"]
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://example.com"]
      interval: 1m30s
      timeout: 30s
      retries: 20
    secrets:
      - NGROK_AUTH_TOKEN
  