version: '3.9'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
    secrets:
      - OPENAI_KEY
    deploy:
      resources:
        reservations:
          memory: 50M
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
secrets:
  OPENAI_KEY:
    external: true
