version: '3.9'
services:
  metabase:
    image: "metabase/metabase:latest"
    ports:
      - mode: ingress
        target: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "metabase"
      MB_DB_HOST: "raphaeltm-postgres"
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 1024M
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "metabase"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 1024M