version: '3'
name: nextjs
services:
  web:
    domainname: nextjs.defang.chewydemos.com
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - target: 3000
        mode: ingress
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M