version: '3'
services:
  imgproxy:
    restart: unless-stopped
    image: darthsim/imgproxy
    ports:
      - mode: ingress
        target: 8080
        protocol: http
    deploy:
      resources:
        reservations:
          memory: 256M
