# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
, unzip
}:
let
  shaMap = {
    x86_64-linux = "0gfi9pj2dgmqkhhfaz3s7f8lkz0q0a30h6cz8baj22586rvmvmfx";
    aarch64-linux = "0pdzgskxrbz6z32pvb3dmv05by4whnml6q1h4gs5mxqcnyfw7x3s";
    x86_64-darwin = "1ly56g7nd8wm2zq184078yjrrzf2b5rb3kkl8zn78hns2mdhbxgm";
    aarch64-darwin = "1ly56g7nd8wm2zq184078yjrrzf2b5rb3kkl8zn78hns2mdhbxgm";
  };

  urlMap = {
    x86_64-linux = "https://github.com/DefangLabs/defang/releases/download/v0.5.49/defang_0.5.49_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/DefangLabs/defang/releases/download/v0.5.49/defang_0.5.49_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/DefangLabs/defang/releases/download/v0.5.49/defang_0.5.49_macOS.zip";
    aarch64-darwin = "https://github.com/DefangLabs/defang/releases/download/v0.5.49/defang_0.5.49_macOS.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "defang";
  version = "0.5.49";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./defang $out/bin/defang
  '';
  postInstall = ''
    installShellCompletion --cmd defang \
    --bash <($out/bin/defang completion bash) \
    --zsh <($out/bin/defang completion zsh) \
    --fish <($out/bin/defang completion fish)
  '';

  system = system;

  meta = {
    description = "Defang is the easiest way for developers to create and deploy their containerized applications";
    homepage = "https://defang.io/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
