# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
, makeWrapper
, stdenv
, unzip
}:
let
  shaMap = {
    x86_64-linux = "1h3cprak54g65bf2v4yjgih2x4jwri80h224czi1yv5054lp66hb";
    aarch64-linux = "0y11sx9kn45gi5lv2s2ff9sncsracyx2f8vqabyv9l9ld05d414b";
    x86_64-darwin = "1lbkha3m4nr7nrq2hliiza494a3acp0a21qxz2c1hagr5b419yxl";
    aarch64-darwin = "1lbkha3m4nr7nrq2hliiza494a3acp0a21qxz2c1hagr5b419yxl";
  };

  urlMap = {
    x86_64-linux = "https://github.com/defang-io/defang/releases/download/v0.4.56/defang_0.4.56_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/defang-io/defang/releases/download/v0.4.56/defang_0.4.56_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/defang-io/defang/releases/download/v0.4.56/defang_0.4.56_macOS.zip";
    aarch64-darwin = "https://github.com/defang-io/defang/releases/download/v0.4.56/defang_0.4.56_macOS.zip";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "defang";
  version = "0.4.56";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./defang $out/bin/defang
  '';

  system = system;

  meta = {
    description = "Command-line interface for the Defang Opinionated Platform";
    homepage = "https://defang.io/";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
