# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: defang
builds:
  - id: defang-mac
    main: ./cmd/cli
    binary: defang
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - ./bin/codesign.sh "{{ .Path }}"

  - id: defang-cli
    main: ./cmd/cli
    binary: defang
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

source:
  enabled: false

universal_binaries:
  - id: defang-macfat
    ids:
      - defang-mac
    replace: true
    hooks:
      post:
        - ./bin/codesign.sh "{{ .Path }}"

archives:
  - format_overrides:
      - goos: darwin
        format: zip
      - goos: windows
        format: zip
    # replace "darwin" with "macOS" in the filename; replace "all" with ""; NOTE: if you change this, also change go.yml GitHub Actions workflow
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}{{ if ne .Arch "all" }}_{{ .Arch }}{{ end }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

release:
  github:
    owner: defang-io
    name: defang
  header: |
    # Defang CLI
    This is the Command Line Interface (CLI) for [Defang](https://defang.io). This is a beta version and is provided as-is, intended primarily for testing purposes.
    For alternative installation methods, please check the [README](https://github.com/defang-io/defang/blob/main/README.md).
    ## Manual installation Instructions
    1. Download the archive file for your Operating System.
    2. Extract the archive. This should reveal the binary file for Defang.
    3. Manually place the binary file in a directory that's included in your system's `PATH` environment variable.
    ### Additional Step for MacOS Users
    MacOS users will need to allow the binary to run due to security settings:
    1. Attempt to run the binary. You'll see a security prompt preventing you from running it.
    2. Go to System Preferences > Privacy & Security > General.
    3. In the 'Allow applications downloaded from:' section, you should see a message about Defang being blocked. Click 'Open Anyway'.
    4. Alternatively, select the option "App Store and identified developers" to allow all applications from the App Store and identified developers to run.

    Please remember this software is in beta, so please report any issues or feedback through our GitHub page. Your help in improving Defang is greatly appreciated!
  # mode: keep-existing
  # draft: true
  # replace_existing_draft: true
  # prerelease: "true"

nix:
  # commit_author: defang-io
  - homepage: https://defang.io/
    description: Command-line interface for the Defang Opinionated Platform
    license: "mit"
    repository:
      owner: defang-io
      name: defang
