version: '3.9'
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
        published: 8080
    environment:
      - MONGO_URI=mongodb+srv://ichrisjiang:Chris6211@cluster0.sduawcf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
