version: '3.9'
services:
  llama:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODEL=phi
    ports:
      - 5000:5000
    volumes:
      - ./defang-llama:/app
      - ./.data/ollama:/root/.ollama