name: Build and Publish JSON

on:
  push:
    branches: build-samples-json # TODO: Change to main (deploy test)
    paths:
      - 'samples/**'

jobs:
  build-json:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger CLI Autodoc
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.DOCS_ACTION_TRIGGER_TOKEN }}
            repository: defang-io/defang-docs
            event-type: sample-update
