name: Trigger Docs Samples Rebuild

on:
  push:
    branches: main
    paths:
      - 'samples/**'

jobs:
  build-json:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger CLI Autodoc
          uses: peter-evans/repository-dispatch@v1
          with:
            token: ${{ secrets.DOCS_ACTION_TRIGGER_TOKEN }}
            repository: DefangLabs/defang-docs
            event-type: sample-update
