name: Docker

on:
  release:
    types: [published]
  push:
    branches:
      - "kevin/githubAction"
    paths:
      - '.github/workflows/docker.yml'
      - 'src/Makefile'

jobs:
    push-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU (for multi-arch builds)
              uses: docker/setup-qemu-action@v3

            - name: Build and push Docker images and manifests
              run: cd src && make push-images