name: Nightly Build

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:     # optional: allows manual runs

permissions:
  contents: read

jobs:
  goreleaser-nightly:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # Get go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

        # Execute goreleaser nightly run (see .goreleaser.yml nightly for details)
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}