name: Nightly Build

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:     # optional: allows manual runs

permissions:
  contents: write

jobs:
  goreleaser-nightly:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        # Get go
      - uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum
        # Execute goreleaser nightly run (see .goreleaser.yml nightly for details)
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          workdir: src
          args: release --clean --nightly --skip=announce --config=.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
