# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Defang NPM Package

# This event will only trigger a workflow run if the workflow file is on the default branch.
on:
  workflow_run:
    workflows: [Go package]
    types: [completed]
    branches: [main]

env:
  DEFANG_CLI_RELEASE_VERSION: ${{ github.ref_name }}
  NODE_VERSION: "21"
  NPM_REGISTRY_URL: "https://registry.npmjs.org"

jobs:
  publish-npm-binaries:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(${{github.ref_name}}, 'v')

    defaults:
      run:
        shell: bash
        working-directory: ./pkgs/npm

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Publish to NPM
        run: |
          #update version placeholder in package.json with version matching binary.
          npm version ${{ env.DEFANG_CLI_RELEASE_VERSION }}

          # install dependencies
          npm ci --ignore-scripts

          #build
          npm run build

          #make the cli.js executable
          chmod u+x ./bin/cli.js

          # publish the package
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
