name: NPM package

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/npm.yml"
      - ".github/actions/npm-build/**"
      - "pkgs/npm/**"

permissions:
  contents: read

jobs:
  npm-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build and test npm package
        uses: ./.github/actions/npm-build

      - name: Test npm package
        shell: bash
        working-directory: "./pkgs/npm"
        run: npm test
