name: NPM package

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/npm.yml"
      - ".github/actions/npm-build/**"
      - "pkgs/npm/**"

permissions:
  contents: read

jobs:
  npm-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and test npm package
        uses: ./.github/actions/npm-build

      - name: Test npm package
        shell: bash
        working-directory: "./pkgs/npm"
        run: npm test
