name: Smoke Tests

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  trigger-smoketests:
    name: Trigger CLI Smoke Tests
    runs-on: ubuntu-latest
    concurrency:
      group: smoketests-${{ github.ref }}
      cancel-in-progress: false
    environment: smoketest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          # If this token is expired, you can regenerate by following these steps:
          # 1. Navigate to https://github.com/settings/personal-access-tokens/new
          # 2. Fill out the form with the following values:
          #   * Token name: defang-mvp-workflow-dispatch-token
          #   * Description: This token will be used by a workflow in the `DefangLabs/defang` repository to trigger a workflow run in the `DefangLabs/defang-mvp` repository.
          #   * Resource Owner: Defang Labs
          #   * Expiration: 366 days
          #   * Repositories:
          #     * DefangLabs/defang-mvp
          #   * Repository Permissions:
          #     * Actions (read and write access)
          #     * Metadata (read only)
          # 3. Click "Generate token"
          # 4. Copy the new token into the `DEFANG_MVP_ACTIONS_DISPATCH_TOKEN` secret in the `smoketest` environment
          github-token: ${{ secrets.DEFANG_MVP_ACTIONS_DISPATCH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'DefangLabs',
              repo: 'defang-mvp',
              workflow_id: 'cli-smoketests.yml',
              ref: 'main',
              inputs: {
                'sample-name': 'html-css-js'
              }
            });
